server:
  port: 1017
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: lianjiang
  username: root
  password: 123456
  charset: utf8
  loc: Asia/Shanghai
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
rabbitmq:
  username: MGAronya
  password: MGAronya
  host: 127.0.0.1
  port: 5672
  virtual: MGAronya
